# network_mode "host" needed to make bluetooth work inside of hass container

version: '2.4'
services:
  mariadb:
    image: tobi312/rpi-mariadb
    container_name: mariadb
    network_mode: "host"
    logging:
      driver: "local"
      options:
        max-size: "500k"
        max-file: "3"
    restart: unless-stopped
    volumes:
      - /home/homeassistant/hassdb:/var/lib/mysql
      #- /etc/mysql/mariadb.conf.d:/etc/mysql/conf.d
    env_file:
      - ./common.env
    environment:
      TZ: Asia/Jerusalem
      MYSQL_RANDOM_ROOT_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    #ports:
    #  - 3306:3306
    healthcheck:
      #test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1
      test:  mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1
      interval: 60s
      timeout: 60s
      retries: 5
      #start_period: 30s
      
  rabbitmq:
    image: rabbitmq:3.9.12-management
    container_name: rabbitmq
    network_mode: "host"
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    logging:
      driver: "local"
      options:
        max-size: "100k"
        max-file: "3"    
    restart: unless-stopped
    #ports:
    #  - 5672:5672
    #  - 15672:15672
    volumes:
      - /var/lib/rabbitmq/:/var/lib/rabbitmq/  
      - ./config/rabbitmq/:/etc/rabbitmq/    
      
  homeassistant:
    image: homeassistant/raspberrypi4-homeassistant:2021.12.7
    container_name: homeassistant
    network_mode: "host"
    logging:
      driver: "local"
      options:
        max-size: "500k"
        max-file: "3"
    restart: unless-stopped
    devices:  
      - /dev/i2c-1:/dev/i2c-1
      - /dev/vhci:/dev/vhci
      - /dev/gpiomem:/dev/gpiomem
      - /dev/ttyAMA0:/dev/ttyAMA0
    #  - /dev/i2c-6:/dev/i2c-6      
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/homeassistant/hass:/config
      - /srv/homeassistant/:/test
    #ports:
    #  - 8123:8123
    depends_on:
      - "mariadb"
      - "rabbitmq"

  gesture_sensor:
    image: gesture_sensor
    container_name: gesture_sensor
    network_mode: "host"
    env_file:
      - ./common.env    
    logging:
      driver: "local"
      options:
        max-size: "50k"
        max-file: "3"    
    restart: unless-stopped
    devices:  
      - /dev/i2c-6:/dev/i2c-6
    depends_on:
      - "homeassistant"