version: '2.4'
services:
  homeassistant:
    image: homeassistant/raspberrypi4-homeassistant:2021.12.7
    container_name: homeassistant
    logging:
      driver: "local"
      options:
        max-size: "500k"
        max-file: "3"
    restart: unless-stopped
    network_mode: host
    devices:  
      - /dev/i2c-1:/dev/i2c-1
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/homeassistant/hass:/config
    #ports:
    #  - 8123:8123
    depends_on:
      - "mariadb"
      - "rabbitmq"
  mariadb:
    image: tobi312/rpi-mariadb
    container_name: mariadb
    logging:
      driver: "local"
      options:
        max-size: "500k"
        max-file: "3"
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/homeassistant/hassdb:/var/lib/mysql
      #- /etc/mysql/mariadb.conf.d:/etc/mysql/conf.d
    env_file:
      - ./common.env
    environment:
      TZ: Asia/Jerusalem
      MYSQL_RANDOM_ROOT_PASSWORD:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    #ports:
    #  - 3306:3306
    healthcheck:
      test:  mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD || exit 1
      #test:  mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD || exit 1
      interval: 60s
      timeout: 60s
      retries: 5
      #start_period: 30s
  rabbitmq:
    image: rabbitmq:3.8.16-management
    container_name: rabbitmq
    logging:
      driver: "local"
      options:
        max-size: "100k"
        max-file: "3"    
    restart: unless-stopped
    network_mode: host
    #ports:
    #  - 5672:5672
    #  - 15672:15672
    volumes:
      - /var/lib/rabbitmq/:/var/lib/rabbitmq/      
  gesture_sensor:
    image: gesture_sensor
    container_name: gesture_sensor
    logging:
      driver: "local"
      options:
        max-size: "50k"
        max-file: "3"    
    restart: unless-stopped
    network_mode: host 
    devices:  
      - /dev/i2c-6:/dev/i2c-6
    depends_on:
      - "homeassistant"